name: Request alias name
description: Request an alias name for your Pactus account or validator address
title: Request alias name for [service name]
labels: ["alias"]
assignees:
  - Mr-HoDL58
  - ja7ad
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form with details about the alias name for your Pactus account or validator address.
  - type: dropdown
    id: network
    attributes:
      label: Network
      description: Alias for which network [mainnet, testnet]
      options:
        - Mainnet
        - Testnet
    validations:
      required: true
  - type: textarea
    id: addresses
    attributes:
      label: Addresses
      description: |
         Pactus accounts or validator address, You can submit a single address or multiple addresses.
         Each line is an address validator or account.
         For Example: 
            - account:pc1z...
            - validator:pc1p...
      value: |
        - account:[address]
        - validator:[address]
        - account:[address]
      render: markdown
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Service name
      description: Please enter your service name
      placeholder: ex. Dezh Technology
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website
      description: What website is the Pactus account or validator address associated with?
      placeholder: https://example.com
    validations:
      required: false
  - type: input
    id: email
    attributes:
      label: Email
      description: Business email address
      placeholder: foobar@example.com
    validations:
      required: false
  - type: input
    id: icon
    attributes:
      label: Icon png 32x32
      description: Add icon for alias name
      placeholder: https://file.example.com/icon32x32.png
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please provide more details about your address.
    validations:
      required: false
